### PR TITLE
fix issue #13 created buttons to stop and clear page view

### PR DESCRIPTION
**Pull request by Matrx123**
Fixes done #13 Created Button to clear and stop and code generation

## Description
On the landing page search bar there were no buttons to stop the code generation and clearing the page view which was forcing user to reload the page. 
In this change these two buttons has been added. 

## Related Issue
None

## Motivation and Context
It prevents the user to do forceful page reload to stop and clear the result on the page view.

## How Has This Been Tested?
1-entered the query on the search bar and wait for some code to be generated.
2-Hit "Stop generating" to stop the response and local state was updated by using the ```stop()``` from ```useChat``` imported from ```ai/react```

**Test Configuration**:
* OS: Ubuntu
* Browser: Firefox
* version: -

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by zinedkaloc** [comment]
Hey @Matrx123, thank you so much for your efforts! ⭐️ 

I have a couple of suggestions that could help enhance the feature. 
As you know, we're using emojis for the icon set. Could we implement something like the following?

- [ ] Have the 'Stop' and 'Clear' buttons visible only in the address bar.

I've created a visual representation for better clarity:

image

What do you think?

**Comment by Matrx123** [comment]
HI @zinedkaloc yeah sure, will do that 🙂

**Comment by Matrx123** [comment]
hi @zinedkaloc pushed the changes, i need to work on the styling of the icons to move them to right end.

**Comment by zinedkaloc** [comment]
closes #13

**Pull request merged**
